#cloud-config
package_upgrade: true
packages:
  - python3-pip
  - python3-venv

write_files:
  - path: /opt/app/app.py
    permissions: '0644'
    content: |
      from flask import Flask, jsonify
      app = Flask(__name__)

      @app.route('/')
      def health_check():
          return jsonify({"status": "success", "message": "Arquitectura de 3 Capas en Azure operativa"})

      if __name__ == '__main__':
          app.run(host='0.0.0.0', port=8080)

  - path: /etc/systemd/system/flaskapp.service
    permissions: '0644'
    content: |
      [Unit]
      Description=Servicio web Flask
      After=network.target

      [Service]
      User=root
      WorkingDirectory=/opt/app
      ExecStart=/opt/app/venv/bin/python /opt/app/app.py
      Restart=always

      [Install]
      WantedBy=multi-user.target

runcmd:
  - python3 -m venv /opt/app/venv
  - /opt/app/venv/bin/pip install flask
  - systemctl daemon-reload
  - systemctl enable flaskapp
  - systemctl start flaskapp